# 파이프라인 배포용---------------------------------------------------------------------------------------------

ersion: "3.2"
services:
  web:
    container_name: tk_web
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    image: kimgh5303/tk_web:tier # 이전에 빌드된 이미지 사용
    ports:
      - "80:80" # 컨테이너의 80 포트를 호스트의 80 포트에 바인딩
    networks:
      - web # web 네트워크에 연결
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/log:/var/log/nginx/
networks:
  web:
    external: true