# 빌드 스테이지
FROM node:13.12.0-alpine as build

# git 설치
RUN apk add --no-cache git

# 작업 디렉터리 설정
WORKDIR /app

# 환경 변수 PATH 설정
ENV PATH /app/node_modules/.bin:$PATH

# 의존성 파일 복사
COPY package.json package-lock.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 파일 복사
COPY . ./

# 애플리케이션 빌드
RUN npm run build

# 서버 스테이지
FROM nginx:alpine

# Nginx 설정 파일 복사
COPY ./default.conf /etc/nginx/conf.d/default.conf

# 빌드된 정적 파일을 Nginx 서버로 복사
COPY --from=build /app/build /usr/share/nginx/html

# 포그라운드에서 Nginx 실행
ENTRYPOINT ["nginx", "-g", "daemon off;"]
